### ISSUE TITLE
Navigator.SceneConfigs.FloatFromBottom 

### ISSUE THREAD

**Issue by KeithZhang** [facebook/rebound-js#21]
I use Navigator to push to a Component with the Navigator.SceneConfigs.FloatFromBottom, and following is the resources:
 
FloatFromLeft: {
    ...BaseConfig,
    animationInterpolators: {
      into: buildStyleInterpolator(FromTheLeft),
      out: buildStyleInterpolator(FadeToTheRight),
    },
  },

var ToTheBack = {
  // Rotate *requires* you to break out each individual component of
  // rotation (x, y, z, w)
  transformTranslate: {
    from: {x: 0, y: 0, z: 0},
    to: {x: 0, y: 0, z: 0},
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },
  transformScale: {
    from: {x: 1, y: 1, z: 1},
    to: {x: 0.95, y: 0.95, z: 1},
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true
  },
  opacity: {
    from: 1,
    to: 0.3,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: false,
    round: 100,
  },
  scaleX: {
    from: 1,
    to: 0.95,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true
  },
  scaleY: {
    from: 1,
    to: 0.95,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true
  },
};

I really want to get the result like follow picture:
![image](https://cloud.githubusercontent.com/assets/2190059/11786032/68417808-a2bf-11e5-881d-682e92179e74.png)

so i add some config into ToTheBack, 
translateY: {
    from: 0,
    to: SCREEN_HEIGHT/3,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },

but it doesn't work, i still get the result like follow picture:
![image](https://cloud.githubusercontent.com/assets/2190059/11785944/053ef8f2-a2bf-11e5-9106-f84d5bdf2793.png)

does the translateY not work?

**Comment by willbailey** [comment]
I think you meant to open this as an issue on ReactNative rather than Rebound.
