### ISSUE TITLE
Dropping Bower support

### ISSUE THREAD

**Issue by wbinnssmith** [facebook/rebound-js#42]
For the past year, [Bower has been recommending migrating away](https://bower.io/blog/2017/how-to-migrate-away-from-bower/) and has pushed [yarn as a replacement](https://bower.io/blog/2016/using-bower-with-yarn/). They've even written [a guide for maintainers for how to politely drop support](https://bower.io/blog/2017/how-to-drop-bower-support/).

I'd like to make our most recent release (from 2014), v0.0.10, the last to support bower. Moving forward we will continue to publish to npm.

New in the npm builds will be the minified version of rebound, so that it can be hosted for us on [`unpkg`](https://unpkg.com/#/), exactly as [React has done](https://github.com/reactjs/react-bower). Bower users can continue to use the latest version of rebound simply by using the https reference to unpkg.

This will have no effect on existing bower users, as we will not unpublish rebound from the bower registry, and instead will simply not provide a `bower.json` or build artifacts in the repo  in upcoming tags.

Please let me know what you think, and if you believe there's a reason to continue to support bower moving forward.

**Comment by JoelMarcey** [comment]
I think this seems reasonable, particularly given that there is a workaround path for Bower users and is not breaking existing ones. I don't see a reason to continue bower support given that and the fact that Bower is strongly recommending yarn anyway.
